spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/issuetracker
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    #        show_sql: true
logging:
  level:
    kr.codesquad.issuetracker: DEBUG
